name: virtuales
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+1 #Recursos Básicos
  cloud_firestore: ^0.13.0+1 #banco de Dados
  link: ^1.1.0
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "images/virtuales.png"
  adaptive_icon_foreground: "images/virtuales.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/Administração e Negócios.jpg
   - images/Animais de Estimação.jpg
   - images/Arquitetura e Engenharia.jpg
   - images/Artes e Música.jpg
   - images/Auto-ajuda e Desenvolvimento Pessoal.jpg
   - images/Automóveis.jpg
   - images/Blogs e Redes Sociais.jpg
   - images/Casa e Jardinagem.jpg
   - images/Culinária e Gastronomia.jpg
   - images/Design e Templates PSD, PPT ou HTML.jpg
   - images/Edição de Áudio, Vídeo ou Imagens.jpg
   - images/Educacional, Cursos Técnicos e Profissionalizantes.jpg
   - images/Eletrodomésticos.jpg
   - images/Eletrônicos.jpg
   - images/Eletroportáteis.jpg
   - images/Entretenimento, Lazer e Diversão.jpg
   - images/Esportes e Fitness.jpg
   - images/Filmes e Cinema.jpg
   - images/Histórias em Quadrinhos.jpg
   - images/Idiomas.jpg
   - images/Informática.jpg
   - images/Internet Marketing.jpg
   - images/Investimentos e Finanças.jpg
   - images/Jogos de Cartas, Poker, Loterias.jpg
   - images/Jogos de Computador, Jogos Online.jpg
   - images/Jurídico.jpg
   - images/Literatura e Poesia.jpg
   - images/Marketing de Rede.jpg
   - images/Marketing e Comunicação.jpg
   - images/Meio Ambiente.jpg
   - images/Moda e vestuário.jpg
   - images/Moveis e decoração.jpg
   - images/Música, Bandas e Shows.jpg
   - images/Paquera, Sedução e Relacionamentos.jpg
   - images/Perfumaria.jpg
   - images/Pessoas com deficiência.jpg
   - images/Plugins, Widgets e Extensões.jpg
   - images/Produtividade e Organização Pessoal.jpg
   - images/Produtos infantis.jpg
   - images/Relatórios, Artigos e Pesquisas.jpg
   - images/Religião e Crenças.jpg
   - images/Romances, Dramas, Estórias e Contos.jpg
   - images/RPG e Jogos de Mesa.jpg
   - images/Saúde, Bem-estar e Beleza.jpg
   - images/Segurança do Trabalho.jpg
   - images/Sexologia e Sexualidade.jpg
   - images/Turismo.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
